# CodeOS configuration for aarch64-softmmu

# Boards: only virt machine remains.
CONFIG_ARM_VIRT=y

# Not selected by default for TCG-enabled builds; we want none of the
# extra 32-bit boards.
CONFIG_CUBIEBOARD=n
CONFIG_EXYNOS4=n
CONFIG_HIGHBANK=n
CONFIG_INTEGRATOR=n
CONFIG_FSL_IMX31=n
CONFIG_MUSICPAL=n
CONFIG_MPS3R=n
CONFIG_MUSCA=n
CONFIG_SX1=n
CONFIG_STELLARIS=n
CONFIG_STM32VLDISCOVERY=n
CONFIG_B_L475E_IOT01A=n
CONFIG_REALVIEW=n
CONFIG_VERSATILE=n
CONFIG_VEXPRESS=n
CONFIG_ZYNQ=n
CONFIG_NPCM7XX=n
CONFIG_COLLIE=n
CONFIG_ASPEED_SOC=n
CONFIG_NETDUINO2=n
CONFIG_NETDUINOPLUS2=n
CONFIG_OLIMEX_STM32_H405=n
CONFIG_MPS2=n
CONFIG_RASPI=n
CONFIG_DIGIC=n
CONFIG_SABRELITE=n
CONFIG_EMCRAFT_SF2=n
CONFIG_MICROBIT=n
CONFIG_FSL_IMX25=n
CONFIG_FSL_IMX7=n
CONFIG_FSL_IMX6UL=n
CONFIG_ALLWINNER_H3=n
CONFIG_VMAPPLE=n

# Kept devices (virt machine):
CONFIG_PCI_DEVICES=y
CONFIG_E1000_PCI=y
CONFIG_VIRTIO_NET=y
CONFIG_VIRTIO_PCI=y
CONFIG_USB_EHCI_SYSBUS=y
CONFIG_USB_XHCI_SYSBUS=y
CONFIG_USB_HID=y
CONFIG_SERIAL_MM=y
CONFIG_VGA=y